---
- name: Update repository indexes
  hosts: all
  become: true
  tasks:
  
    - name: Update repository index (Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- name: Install and configure Controller role
  hosts: Controller
  become: true
  roles:
    - Controller

- name: Install and configure Compute role
  hosts: Compute
  become: true
  roles:
    - Compute

- name: Install and configure Database role
  hosts: Database
  become: true
  roles:
    - Database

- name: Install and configure Message Queue role
  hosts: MessageQueue
  become: true
  roles:
    - MessageQueue

- name: Install and configure Memcached role
  hosts: Memcached
  become: true
  roles:
    - Memcached

- name: Install and configure Etcd role
  hosts: Etcd
  become: true
  roles:
    - Etcd
    
